#!/bin/sh /etc/rc.common
#
# Copyright (C) 2016 Jian Chang <aa65535@live.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=75
USE_PROCD=1
NAME=shadowsocks
SECTION=dns-forwarder

uci_get_by_type() {
	local ret=$(uci get $NAME.@$1[0].$2 2>/dev/null)
	echo ${ret:=$3}
}

start_service() {
	local enable=$(uci_get_by_type $SECTION enable 0)
	[ "$enable" = 1 ] || return 0
	procd_open_instance
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param command /usr/bin/dns-forwarder
	procd_append_param command "-b 127.0.0.1"
	procd_append_param command "-p 5353"
	procd_append_param command "-s" $(uci_get_by_type $SECTION dns_servers 8.8.8.8)
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger $NAME
}
